location /.well-known/matrix/client {
    default_type application/json;
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
    add_header Access-Control-Allow-Headers "X-Requested-With, Content-Type, Authorization";
    return 200 '{"m.homeserver":{"base_url":"https://matrix.palmcoasty.com"},"org.matrix.msc4143.rtc_foci":[{"type":"livekit","livekit_service_url":"https://matrix.palmcoasty.com/livekit/jwt"}]}';
}

location /.well-known/matrix/server {
    default_type application/json;
    add_header Access-Control-Allow-Origin *;
    return 200 '{"m.server":"matrix.palmcoasty.com:443"}';
}
